/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
  "soliscloud adapter settings": {
    en: "Adapter settings for soliscloud",
    de: "Adaptereinstellungen für soliscloud",
    ru: "Настройки адаптера для soliscloud",
    pt: "Configurações do adaptador para soliscloud",
    nl: "Adapterinstellingen voor soliscloud",
    fr: "Paramètres d'adaptateur pour soliscloud",
    it: "Impostazioni dell'adattatore per template",
    es: "Ajustes del adaptador para soliscloud",
    pl: "Ustawienia adaptera dla soliscloud",
    uk: "Налаштування адаптера для soliscloud",
    "zh-cn": "soliscloud 的适配器设置",
  },
  apiKey: {
    en: "apiKey",
    de: "apiKey",
    ru: "APIKey",
    pt: "Chave API",
    nl: "API sleutel",
    fr: "clé API",
    it: "apiKey",
    es: "Clave API",
    pl: "Klucz API",
    uk: "apiKey",
    "zh-cn": "API密钥",
  },
  apiSecret: {
    en: "apiSecret",
    de: "apiSecret",
    ru: "APISecret",
    pt: "apiSecret",
    nl: "apiGeheim",
    fr: "apiSecret",
    it: "apiSecret",
    es: "apiSecret",
    pl: "apiSecret",
    uk: "apiSecret",
    "zh-cn": "api秘密",
  },
  plantID: {
    en: "plantId",
    de: "plantId",
    ru: "идентификатор растения",
    pt: "plantaId",
    nl: "plantId",
    fr: "IDplante",
    it: "IDpianta",
    es: "ID de planta",
    pl: "identyfikator rośliny",
    uk: "plantId",
    "zh-cn": "植物ID",
  },
  pollInterval: {
    en: "pollInterval",
    de: "pollInterval",
    ru: "опросИнтервал",
    pt: "pollInterval",
    nl: "pollInterval",
    fr: "Intervalle de sondage",
    it: "pollInterval",
    es: "intervalo de encuesta",
    pl: "ankietaInterwał",
    uk: "pollInterval",
    "zh-cn": "轮询间隔",
  },
};
